// Keep as Server Component (remove 'use client')
 import "./globals.css";
 // Removed usePathname import
 import UserButton from "@/components/UserButton"; // Keep if used directly here, otherwise remove
 // Removed Toaster, InstallPwaButton, MobileAppBar imports as they are in ClientLayout
 import FuturisticNavBar from "@/components/FuturisticNavBar"; // Keep if needed, though it's commented out below
 import ClientLayout from './ClientLayout'; // Import the new ClientLayout

 // Metadata export remains here
 export const metadata = {
   title: "100 Destinos",
   description: "Generated by create next app",
 };

 export default function RootLayout({ children }) {
   // Removed pathname logic

   return (
     <html lang="en">
       <head>
         <meta name="theme-color" content="#000000" />
         <link rel="manifest" href="/manifest.json" />
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
       </head>
       <body>
         {/* Wrap children with ClientLayout */}
         <ClientLayout>
           {children}
         </ClientLayout>
         {/* <FuturisticNavBar /> from-orange-900 via-gray-900 to-black*/}
         {/* Removed InstallPwaButton, MobileAppBar, Toaster direct rendering */}
       </body>
     </html>
   );
 }
