const USD_TO_AOA_RATE = 900;

const hotels = [
  {
    id: 'palmeiras',
    name: 'Hotel Palmeiras',
    location: 'Luanda, Angola',
    rating: 4.7,
    description: 'Um hotel luxuoso que oferece uma escapada serena com comodidades modernas e vistas deslumbrantes.',
    images: [
      '/hotels/Palmeiras/intresting spots/breakfast.jpg',
      '/hotels/Palmeiras/intresting spots/dj.jpg',
      '/hotels/Palmeiras/intresting spots/gym.jpg',
      '/hotels/Palmeiras/intresting spots/jacuzzi.jpg',
      '/hotels/Palmeiras/intresting spots/roof_top_restaruante.jpg',
    ],
    rooms: [
      {
        id: 'palmeiras-twin-standard',
        name: 'Suite Twin Standard',
        guestCapacity: {
          maxPeople2: 2,
          price2: 353 * USD_TO_AOA_RATE,
          maxPeople1: 1,
          price1: 300 * USD_TO_AOA_RATE,
        },
        bedding: '2 camas de solteiro',
        area: '30 m²',
        images: [
          '/hotels/Palmeiras/Suite Twin Standard/1.jpg',
          '/hotels/Palmeiras/Suite Twin Standard/2.jpg',
          '/hotels/Palmeiras/Suite Twin Standard/3.jpg',
          '/hotels/Palmeiras/Suite Twin Standard/4.jpg',
          '/hotels/Palmeiras/Suite Twin Standard/5.jpg',
        ],
        amenities: [
          { icon: '👶', text: 'Crib: Free upon request' },
          { icon: '🍳', text: 'Private Kitchenette' },
          { icon: '🚿', text: 'In-room Bathroom' },
          { icon: '🌳', text: 'Garden view' },
          { icon: '🏙️', text: 'City view' },
          { icon: '🏊', text: 'Pool with a view' },
          { icon: '⬆️🏊', text: 'Rooftop pool' },
          { icon: '❄️', text: 'Air conditioning' },
          { icon: '📺', text: 'Flat-screen TV' },
          { icon: '🔇', text: 'Soundproofing' },
          { icon: '🧺', text: 'Minibar' },
          { icon: '📶', text: 'Free Wi-Fi' },
          { icon: '🧴', text: 'Free toiletries' },
          { icon: '🧖‍♀️', text: 'Bathrobe' },
          { icon: '🔒', text: 'Safe' },
          { icon: '🚽', text: 'Bidet' },
          { icon: '🚻', text: 'WC' },
          { icon: '🛋️', text: 'Sofa' },
          { icon: '🛁', text: 'Bathtub or shower' },
          { icon: '🧼', text: 'Towels' },
          { icon: '🛏️', text: 'Bed linen' },
          { icon: '🔌', text: 'Socket near the bed' },
          { icon: '🚫🦠', text: 'Hypoallergenic' },
          { icon: 'タイル/大理石の床', text: 'Tile/Marble floor' },
          { icon: '🖥️', text: 'Desk' },
          { icon: '💺', text: 'High chair for babies' },
          { icon: '🛋️', text: 'Seating area' },
          { icon: '🚪', text: 'Private entrance' },
          { icon: '📺', text: 'Television' },
          { icon: 'slippers', text: 'Slippers' },
          { icon: '🧊', text: 'Fridge' },
          { icon: '📞', text: 'Telephone' },
          { icon: '👕', text: 'Ironing facilities' },
          { icon: '☕', text: 'Tea and coffee making facilities' },
          { icon: '♨️', text: 'Microwave' },
          { icon: '🔥', text: 'Heating' },
          { icon: 'hairdryer', text: 'Hair dryer' },
          { icon: '🍳', text: 'Kitchenware' },
          { icon: '🍳', text: 'Kitchenette' },
          { icon: '🌬️', text: 'Fan' },
          { icon: '📏', text: 'Extra-long beds (> 2 meters)' },
          { icon: '👗', text: 'Dressing room' },
          { icon: '🧼', text: 'Towels/linen (additional cost)' },
          { icon: '⏰', text: 'Wake-up service/alarm clock' },
          { icon: 'Carpeted floor', text: 'Carpeted floor' },
          { icon: 'kettle', text: 'Electric kettle' },
          { icon: '📺', text: 'Cable channels' },
          { icon: '⏰', text: 'Wake-up service' },
          { icon: '💻', text: 'Laptop safe' },
          { icon: '👑', text: 'Executive lounge access' },
          { icon: 'Dryer', text: 'Clothes dryer' },
          { icon: '👚', text: 'Wardrobe or closet' },
          { icon: '🍽️', text: 'Dining area' },
          { icon: 'elevator', text: 'Upper floors accessible by elevator' },
          { icon: 'hangers', text: 'Clothes rack' },
          { icon: '🧻', text: 'Toilet paper' },
          { icon: '👶', text: 'Baby safety gates' },
          { icon: '❄️', text: 'Individual air conditioning unit in each room' },
          { icon: '🧴', text: 'Hand sanitizer gel' },
        ],
        inclusions: [
          { icon: '🍳', text: 'Very good breakfast included' },
          { icon: '🅿️', text: 'Parking included' },
          { icon: '⏰', text: 'Late check-in included' },
        ],
      },
      {
        id: 'palmeiras-standard',
        name: 'Suite Standard',
        guestCapacity: {
          maxPeople2: 2,
          price2: 353 * USD_TO_AOA_RATE,
          maxPeople1: 1,
          price1: 300 * USD_TO_AOA_RATE,
        },
        bedding: '1 cama de casal grande',
        area: '30 m²',
        images: [
          '/hotels/Palmeiras/Suite Standard/1.jpg',
          '/hotels/Palmeiras/Suite Standard/2.jpg',
          '/hotels/Palmeiras/Suite Standard/3.jpg',
          '/hotels/Palmeiras/Suite Standard/4.jpg',
          '/hotels/Palmeiras/Suite Standard/5.jpg',
        ],
        amenities: [
          { icon: '👶', text: 'Crib: Free upon request' },
          { icon: '🍳', text: 'Private Kitchenette' },
          { icon: '🚿', text: 'In-room Bathroom' },
          { icon: '🌳', text: 'Garden view' },
          { icon: '🏙️', text: 'City view' },
          { icon: '🏊', text: 'Pool with a view' },
          { icon: '⬆️🏊', text: 'Rooftop pool' },
          { icon: '❄️', text: 'Air conditioning' },
          { icon: '📺', text: 'Flat-screen TV' },
          { icon: '🔇', text: 'Soundproofing' },
          { icon: '🧺', text: 'Minibar' },
          { icon: '📶', text: 'Free Wi-Fi' },
          { icon: '🧴', text: 'Free toiletries' },
          { icon: '🧖‍♀️', text: 'Bathrobe' },
          { icon: '🔒', text: 'Safe' },
          { icon: '🚽', text: 'Bidet' },
          { icon: '🚻', text: 'WC' },
          { icon: '🛋️', text: 'Sofa' },
          { icon: '🛁', text: 'Bathtub or shower' },
          { icon: '🧼', text: 'Towels' },
          { icon: '🛏️', text: 'Bed linen' },
          { icon: '🔌', text: 'Socket near the bed' },
          { icon: '🚫🦠', text: 'Hypoallergenic' },
          { icon: 'タイル/大理石の床', text: 'Tile/Marble floor' },
          { icon: '🖥️', text: 'Desk' },
          { icon: '💺', text: 'High chair for babies' },
          { icon: '🛋️', text: 'Seating area' },
          { icon: '🚪', text: 'Private entrance' },
          { icon: '📺', text: 'Television' },
          { icon: 'slippers', text: 'Slippers' },
          { icon: '🧊', text: 'Fridge' },
          { icon: '📞', text: 'Telephone' },
          { icon: '👕', text: 'Ironing facilities' },
          { icon: '☕', text: 'Tea and coffee making facilities' },
          { icon: '♨️', text: 'Microwave' },
          { icon: '🔥', text: 'Heating' },
          { icon: 'hairdryer', text: 'Hair dryer' },
          { icon: '🍳', text: 'Kitchenware' },
          { icon: '🍳', text: 'Kitchenette' },
          { icon: '🌬️', text: 'Fan' },
          { icon: '📏', text: 'Extra-long beds (> 2 meters)' },
          { icon: '👗', text: 'Dressing room' },
          { icon: '🧼', text: 'Towels/linen (additional cost)' },
          { icon: '⏰', text: 'Wake-up service/alarm clock' },
          { icon: 'Carpeted floor', text: 'Carpeted floor' },
          { icon: 'kettle', text: 'Electric kettle' },
          { icon: '📺', text: 'Cable channels' },
          { icon: '⏰', text: 'Wake-up service' },
          { icon: '💻', text: 'Laptop safe' },
          { icon: '👑', text: 'Executive lounge access' },
          { icon: 'Dryer', text: 'Clothes dryer' },
          { icon: '👚', text: 'Wardrobe or closet' },
          { icon: '🍽️', text: 'Dining area' },
          { icon: 'elevator', text: 'Upper floors accessible by elevator' },
          { icon: 'hangers', text: 'Clothes rack' },
          { icon: '🧻', text: 'Toilet paper' },
          { icon: '👶', text: 'Baby safety gates' },
          { icon: '🛋️', text: 'Sofa bed' },
          { icon: '🧴', text: 'Hand sanitizer gel' },
          { icon: '❄️', text: 'Individual air conditioning unit in each room' },
        ],
        inclusions: [
          { icon: '🍳', text: 'Very good breakfast included' },
          { icon: '🅿️', text: 'Parking included' },
          { icon: '⏰', text: 'Late check-in included' },
        ],
      },
      {
        id: 'palmeiras-junior',
        name: 'Suite Júnior',
        guestCapacity: {
          maxPeople: 4,
          price: 474 * USD_TO_AOA_RATE,
        },
        bedding: 'Quarto 1: 2 camas de solteiro, Quarto 2: 1 cama de casal grande',
        area: '45 m²',
        images: [
          '/hotels/Palmeiras/Suite Junior/1.jpg',
          '/hotels/Palmeiras/Suite Junior/2.jpg',
          '/hotels/Palmeiras/Suite Junior/3.jpg',
          '/hotels/Palmeiras/Suite Junior/4.jpg',
          '/hotels/Palmeiras/Suite Junior/5.jpg',
        ],
        amenities: [
          { icon: '👶', text: 'Crib: Free upon request' },
          { icon: '🍳', text: 'Private Kitchenette' },
          { icon: '🚿', text: 'In-room Bathroom' },
          { icon: '🌳', text: 'Garden view' },
          { icon: '🏙️', text: 'City view' },
          { icon: '🏊', text: 'Pool with a view' },
          { icon: '⬆️🏊', text: 'Rooftop pool' },
          { icon: '❄️', text: 'Air conditioning' },
          { icon: '📺', text: 'Flat-screen TV' },
          { icon: '🔇', text: 'Soundproofing' },
          { icon: '🧺', text: 'Minibar' },
          { icon: '📶', text: 'Free Wi-Fi' },
          { icon: '🧴', text: 'Free toiletries' },
          { icon: '🧖‍♀️', text: 'Bathrobe' },
          { icon: '🔒', text: 'Safe' },
          { icon: '🚿', text: 'Additional bathroom' },
          { icon: '🚽', text: 'Bidet' },
          { icon: '🚻', text: 'WC' },
          { icon: '🛋️', text: 'Sofa' },
          { icon: '🛁', text: 'Bathtub or shower' },
          { icon: '🧼', text: 'Towels' },
          { icon: '🛏️', text: 'Bed linen' },
          { icon: '🔌', text: 'Socket near the bed' },
          { icon: '🚫🦠', text: 'Hypoallergenic' },
          { icon: 'タイル/大理石の床', text: 'Tile/Marble floor' },
          { icon: '🖥️', text: 'Desk' },
          { icon: '💺', text: 'High chair for babies' },
          { icon: '🛋️', text: 'Seating area' },
          { icon: '🚪', text: 'Private entrance' },
          { icon: '📺', text: 'Television' },
          { icon: 'slippers', text: 'Slippers' },
          { icon: '🧊', text: 'Fridge' },
          { icon: '📞', text: 'Telephone' },
          { icon: '👕', text: 'Ironing facilities' },
          { icon: '☕', text: 'Tea and coffee making facilities' },
          { icon: '🚪', text: 'Connecting room(s) available' },
          { icon: '♨️', text: 'Microwave' },
          { icon: '🔥', text: 'Heating' },
          { icon: 'hairdryer', text: 'Hair dryer' },
          { icon: '🍳', text: 'Kitchenware' },
          { icon: '🍳', text: 'Kitchenette' },
          { icon: '🌬️', text: 'Fan' },
          { icon: '🚻', text: 'Additional WC' },
          { icon: '📏', text: 'Extra-long beds (> 2 meters)' },
          { icon: '👗', text: 'Dressing room' },
          { icon: '🧼', text: 'Towels/linen (additional cost)' },
          { icon: '⏰', text: 'Wake-up service/alarm clock' },
          { icon: 'Carpeted floor', text: 'Carpeted floor' },
          { icon: 'kettle', text: 'Electric kettle' },
          { icon: '📺', text: 'Cable channels' },
          { icon: '⏰', text: 'Wake-up service' },
          { icon: '💻', text: 'Laptop safe' },
          { icon: '👑', text: 'Executive lounge access' },
          { icon: 'Dryer', text: 'Clothes dryer' },
          { icon: '👚', text: 'Wardrobe or closet' },
          { icon: '🍽️', text: 'Dining area' },
          { icon: 'elevator', text: 'Upper floors accessible by elevator' },
          { icon: 'hangers', text: 'Clothes rack' },
          { icon: '🧻', text: 'Toilet paper' },
          { icon: '👶', text: 'Baby safety gates' },
          { icon: '🧴', text: 'Hand sanitizer gel' },
          { icon: '❄️', text: 'Individual air conditioning unit in each room' },
        ],
        inclusions: [
          { icon: '🍳', text: 'Very good breakfast included' },
          { icon: '🅿️', text: 'Parking included' },
          { icon: '⏰', text: 'Late check-in included' },
        ],
      },
      {
        id: 'palmeiras-premium',
        name: 'Suite Premium',
        guestCapacity: {
          maxPeople: 4,
          price: 642 * USD_TO_AOA_RATE,
        },
        bedding: 'Quarto 1: 2 camas de solteiro, Quarto 2: 1 cama de casal extra grande',
        area: '45 m²',
        images: [
          '/hotels/Palmeiras/Suite Premium/1.jpg',
          '/hotels/Palmeiras/Suite Premium/2.jpg',
          '/hotels/Palmeiras/Suite Premium/3.jpg',
          '/hotels/Palmeiras/Suite Premium/4.jpg',
          '/hotels/Palmeiras/Suite Premium/5.jpg',
        ],
        amenities: [
          { icon: '👶', text: 'Crib: Free upon request' },
          { icon: '🍳', text: 'Private Kitchenette' },
          { icon: '🚿', text: 'In-room Bathroom' },
          { icon: 'балкон', text: 'Balcony' },
          { icon: '🌳', text: 'Garden view' },
          { icon: '🏙️', text: 'City view' },
          { icon: '🏊', text: 'Pool with a view' },
          { icon: '⬆️🏊', text: 'Rooftop pool' },
          { icon: '❄️', text: 'Air conditioning' },
          { icon: '📺', text: 'Flat-screen TV' },
          { icon: '🔇', text: 'Soundproofing' },
          { icon: 'テラス', text: 'Terrace' },
          { icon: '☕', text: 'Coffee machine' },
          { icon: '🧺', text: 'Minibar' },
          { icon: '📶', text: 'Free Wi-Fi' },
          { icon: '🧴', text: 'Free toiletries' },
          { icon: '🧖‍♀️', text: 'Bathrobe' },
          { icon: '🔒', text: 'Safe' },
          { icon: '🚿', text: 'Additional bathroom' },
          { icon: '🚽', text: 'Bidet' },
          { icon: '🚻', text: 'WC' },
          { icon: '🛋️', text: 'Sofa' },
          { icon: '🛁', text: 'Bathtub or shower' },
          { icon: '🧼', text: 'Towels' },
          { icon: '🛏️', text: 'Bed linen' },
          { icon: '🔌', text: 'Socket near the bed' },
          { icon: '🚫🦠', text: 'Hypoallergenic' },
          { icon: 'タイル/大理石の床', text: 'Tile/Marble floor' },
          { icon: '🖥️', text: 'Desk' },
          { icon: '💺', text: 'High chair for babies' },
          { icon: '🛋️', text: 'Seating area' },
          { icon: '🚪', text: 'Private entrance' },
          { icon: '📺', text: 'Television' },
          { icon: 'slippers', text: 'Slippers' },
          { icon: '🧊', text: 'Fridge' },
          { icon: '📞', text: 'Telephone' },
          { icon: '👕', text: 'Ironing facilities' },
          { icon: '☕', text: 'Tea and coffee making facilities' },
          { icon: 'ironing board', text: 'Iron' },
          { icon: '🚪', text: 'Connecting room(s) available' },
          { icon: '♨️', text: 'Microwave' },
          { icon: '🔥', text: 'Heating' },
          { icon: 'hairdryer', text: 'Hair dryer' },
          { icon: '🍳', text: 'Kitchenware' },
          { icon: '🍳', text: 'Kitchenette' },
          { icon: '🌬️', text: 'Fan' },
          { icon: '🚻', text: 'Additional WC' },
          { icon: '📏', text: 'Extra-long beds (> 2 meters)' },
          { icon: '👗', text: 'Dressing room' },
          { icon: '🧼', text: 'Towels/linen (additional cost)' },
          { icon: '⏰', text: 'Wake-up service/alarm clock' },
          { icon: 'Carpeted floor', text: 'Carpeted floor' },
          { icon: 'kettle', text: 'Electric kettle' },
          { icon: 'outdoor furniture', text: 'Outdoor furniture' },
          { icon: '📺', text: 'Cable channels' },
          { icon: '⏰', text: 'Wake-up service' },
          { icon: '💻', text: 'Laptop safe' },
          { icon: '👑', text: 'Executive lounge access' },
          { icon: 'Dryer', text: 'Clothes dryer' },
          { icon: '👚', text: 'Wardrobe or closet' },
          { icon: '🍽️', text: 'Dining area' },
          { icon: '🍽️', text: 'Dining table' },
          { icon: 'elevator', text: 'Upper floors accessible by elevator' },
          { icon: 'hangers', text: 'Clothes rack' },
          { icon: '🧻', text: 'Toilet paper' },
          { icon: '👶', text: 'Baby safety gates' },
          { icon: '❄️', text: 'Individual air conditioning unit in each room' },
          { icon: '🧴', text: 'Hand sanitizer gel' },
        ],
        inclusions: [
          { icon: '🍳', text: 'Very good breakfast included' },
          { icon: '🅿️', text: 'Parking included' },
          { icon: '⏰', text: 'Late check-in included' },
        ],
      },
      {
        id: 'palmeiras-deluxe',
        name: 'Suite Deluxe',
        guestCapacity: {
          maxPeople: 4,
          price: 737 * USD_TO_AOA_RATE,
        },
        bedding: 'Quarto 1: 2 camas de solteiro, Quarto 2: 1 cama de casal grande, Sala: 3 sofás-cama',
        area: '45 m²',
        images: [
          '/hotels/Palmeiras/Suite Deluxe/1.jpg',
          '/hotels/Palmeiras/Suite Deluxe/2.jpg',
          '/hotels/Palmeiras/Suite Deluxe/3.jpg',
          '/hotels/Palmeiras/Suite Deluxe/4.jpg',
          '/hotels/Palmeiras/Suite Deluxe/5.jpg',
        ],
        amenities: [
          { icon: '👶', text: 'Crib: Free upon request' },
          { icon: '🍳', text: 'Private Kitchenette' },
          { icon: '🚿', text: 'In-room Bathroom' },
          { icon: 'балкон', text: 'Balcony' },
          { icon: '🌳', text: 'Garden view' },
          { icon: '🏙️', text: 'City view' },
          { icon: '🏊', text: 'Pool with a view' },
          { icon: '⬆️🏊', text: 'Rooftop pool' },
          { icon: '❄️', text: 'Air conditioning' },
          { icon: '🛁', text: 'Hot tub' },
          { icon: '📺', text: 'Flat-screen TV' },
          { icon: '🔇', text: 'Soundproofing' },
          { icon: 'テラス', text: 'Terrace' },
          { icon: '☕', text: 'Coffee machine' },
          { icon: '🧺', text: 'Minibar' },
          { icon: '📶', text: 'Free Wi-Fi' },
          { icon: '🛁', text: 'Hot tub' },
          { icon: '🧴', text: 'Free toiletries' },
          { icon: '🧖‍♀️', text: 'Bathrobe' },
          { icon: '🔒', text: 'Safe' },
          { icon: '🚿', text: 'Additional bathroom' },
          { icon: '🚽', text: 'Bidet' },
          { icon: '🚻', text: 'WC' },
          { icon: '🛋️', text: 'Sofa' },
          { icon: '🛁', text: 'Bathtub or shower' },
          { icon: '🧼', text: 'Towels' },
          { icon: '🛏️', text: 'Bed linen' },
          { icon: '🔌', text: 'Socket near the bed' },
          { icon: '🚫🦠', text: 'Hypoallergenic' },
          { icon: 'タイル/大理石の床', text: 'Tile/Marble floor' },
          { icon: '🖥️', text: 'Desk' },
          { icon: '💺', text: 'High chair for babies' },
          { icon: '🛋️', text: 'Seating area' },
          { icon: '🚪', text: 'Private entrance' },
          { icon: '📺', text: 'Television' },
          { icon: 'slippers', text: 'Slippers' },
          { icon: '🧊', text: 'Fridge' },
          { icon: '📞', text: 'Telephone' },
          { icon: '👕', text: 'Ironing facilities' },
          { icon: '☕', text: 'Tea and coffee making facilities' },
          { icon: 'ironing board', text: 'Iron' },
          { icon: '🚪', text: 'Connecting room(s) available' },
          { icon: '♨️', text: 'Microwave' },
          { icon: '🔥', text: 'Heating' },
          { icon: 'hairdryer', text: 'Hair dryer' },
          { icon: '🍳', text: 'Kitchenware' },
          { icon: '🍳', text: 'Kitchenette' },
          { icon: '🌬️', text: 'Fan' },
          { icon: '🚻', text: 'Additional WC' },
          { icon: '📏', text: 'Extra-long beds (> 2 meters)' },
          { icon: '👗', text: 'Dressing room' },
          { icon: '🧼', text: 'Towels/linen (additional cost)' },
          { icon: '⏰', text: 'Wake-up service/alarm clock' },
          { icon: 'Carpeted floor', text: 'Carpeted floor' },
          { icon: 'kettle', text: 'Electric kettle' },
          { icon: 'outdoor furniture', text: 'Outdoor furniture' },
          { icon: '📺', text: 'Cable channels' },
          { icon: '⏰', text: 'Wake-up service' },
          { icon: '💻', text: 'Laptop safe' },
          { icon: '👑', text: 'Executive lounge access' },
          { icon: 'Dryer', text: 'Clothes dryer' },
          { icon: '👚', text: 'Wardrobe or closet' },
          { icon: '🍽️', text: 'Dining area' },
          { icon: '🍽️', text: 'Dining table' },
          { icon: 'elevator', text: 'Upper floors accessible by elevator' },
          { icon: 'hangers', text: 'Clothes rack' },
          { icon: '🧻', text: 'Toilet paper' },
          { icon: '👶', text: 'Baby safety gates' },
          { icon: '🧴', text: 'Hand sanitizer gel' },
          { icon: '❄️', text: 'Individual air conditioning unit in each room' },
        ],
        inclusions: [
          { icon: '🍳', text: 'Very good breakfast included' },
          { icon: '🅿️', text: 'Parking included' },
          { icon: '⏰', text: 'Late check-in included' },
        ],
      },
    ],
  },
  {
    id: 'presidente',
    name: 'Hotel Presidente',
    location: 'Luanda, Angola',
    rating: 4.5,
    description: 'Um hotel clássico no coração da cidade, oferecendo conforto e conveniência.',
    images: [
      '/hotels/Presidente/intresting spots/1.jpg', // Placeholder, need actual images
      '/hotels/Presidente/intresting spots/2.jpg', // Placeholder
    ],
    rooms: [
      {
        id: 'presidente-duplo-standard',
        name: 'Quarto Duplo Standard',
        guestCapacity: {
          maxPeople2: 2,
          price2_breakfast_only: 1540 * USD_TO_AOA_RATE,
          price2_breakfast_dinner: 1836 * USD_TO_AOA_RATE,
          maxPeople1: 1,
          price1_breakfast_only: 1430 * USD_TO_AOA_RATE,
          price1_breakfast_dinner: 1578 * USD_TO_AOA_RATE,
        },
        bedding: '1 cama de casal',
        area: '20 m²',
        images: [
          '/hotels/Presidente/Quarto Duplo Standard/1.jpg', // Placeholder
          '/hotels/Presidente/Quarto Duplo Standard/2.jpg', // Placeholder
        ],
        amenities: [
          { icon: '👶', text: 'Crib: Available upon request' },
          { icon: '🌊', text: 'Sea view' },
          { icon: '🏙️', text: 'City view' },
          { icon: '🏡', text: 'Courtyard view' },
          { icon: '❄️', text: 'Air conditioning' },
          { icon: '🚿', text: 'Private bathroom' },
          { icon: '📺', text: 'Flat-screen TV' },
          { icon: '🔇', text: 'Soundproofing' },
          { icon: '🧺', text: 'Minibar' },
          { icon: '📶', text: 'Free Wi-Fi' },
          { icon: '🧴', text: 'Free toiletries' },
          { icon: '🚿', text: 'Shower' },
          { icon: '🔒', text: 'Safe' },
          { icon: '🚻', text: 'WC' },
          { icon: '🧼', text: 'Towels' },
          { icon: '🛏️', text: 'Bed linen' },
          { icon: '🔌', text: 'Socket near the bed' },
          { icon: '🖥️', text: 'Desk' },
          { icon: '🛋️', text: 'Seating area' },
          { icon: '🚪', text: 'Private entrance' },
          { icon: '📺', text: 'Television' },
          { icon: '🩴', text: 'Slippers' },
          { icon: '🧊', text: 'Fridge' },
          { icon: '📞', text: 'Telephone' },
          { icon: '👕', text: 'Ironing facilities' },
          { icon: '☕', text: 'Tea and coffee making facilities' },
          { icon: '🎞️', text: 'Pay-per-view channels' },
          { icon: 'hairdryer', text: 'Hair dryer' },
          { icon: '⏰', text: 'Wake-up service/alarm clock' },
          { icon: '🧶', text: 'Carpeted floor' },
          { icon: 'Kettle', text: 'Electric kettle' },
          { icon: '📺', text: 'Cable channels' },
          { icon: '⏰', text: 'Wake-up service' },
          { icon: '💻', text: 'Laptop safe' },
          { icon: '👚', text: 'Wardrobe or closet' },
          { icon: '⬆️', text: 'Upper floors accessible by elevator' },
          { icon: 'hangers', text: 'Clothes rack' },
          { icon: '🧻', text: 'Toilet paper' },
          { icon: '🧴', text: 'Hand sanitizer gel' },
        ],
        paymentCancellation: [
          { icon: '✔️', text: 'Free cancellation at any time' },
          { icon: '💳', text: 'No prepayment needed – pay at the accommodation' },
          { icon: '❌', text: 'No credit card required' },
        ],
      },
      {
        id: 'presidente-twin-standard',
        name: 'Quarto Twin Standard',
        guestCapacity: {
          maxPeople2: 2,
          price2_breakfast_only: 1540 * USD_TO_AOA_RATE,
          price2_breakfast_dinner: 1836 * USD_TO_AOA_RATE,
          maxPeople1: 1,
          price1_breakfast_only: 1430 * USD_TO_AOA_RATE,
          price1_breakfast_dinner: 1578 * USD_TO_AOA_RATE,
        },
        bedding: '2 camas de solteiro',
        area: '20 m²',
        images: [
          '/hotels/Presidente/Quarto Twin Standard/1.jpg', // Placeholder
          '/hotels/Presidente/Quarto Twin Standard/2.jpg', // Placeholder
        ],
        amenities: [
          { icon: '👶', text: 'Crib: Available upon request' },
          { icon: '🏙️', text: 'City view' },
          { icon: '❄️', text: 'Air conditioning' },
          { icon: '🚿', text: 'Private bathroom' },
          { icon: '📺', text: 'Flat-screen TV' },
          { icon: '🔇', text: 'Soundproofing' },
          { icon: '🧺', text: 'Minibar' },
          { icon: '📶', text: 'Free Wi-Fi' },
          { icon: '🧴', text: 'Free toiletries' },
          { icon: '🚿', text: 'Shower' },
          { icon: '🔒', text: 'Safe' },
          { icon: '🚻', text: 'WC' },
          { icon: '🧼', text: 'Towels' },
          { icon: '🛏️', text: 'Bed linen' },
          { icon: '🔌', text: 'Socket near the bed' },
          { icon: '🖥️', text: 'Desk' },
          { icon: '🛋️', text: 'Seating area' },
          { icon: '🚪', text: 'Private entrance' },
          { icon: '📺', text: 'Television' },
          { icon: '🩴', text: 'Slippers' },
          { icon: '🧊', text: 'Fridge' },
          { icon: '📞', text: 'Telephone' },
          { icon: '👕', text: 'Ironing facilities' },
          { icon: '☕', text: 'Tea and coffee making facilities' },
          { icon: '🎞️', text: 'Pay-per-view channels' },
          { icon: 'hairdryer', text: 'Hair dryer' },
          { icon: '⏰', text: 'Wake-up service/alarm clock' },
          { icon: '🧶', text: 'Carpeted floor' },
          { icon: 'Kettle', text: 'Electric kettle' },
          { icon: '📺', text: 'Cable channels' },
          { icon: '⏰', text: 'Wake-up service' },
          { icon: '💻', text: 'Laptop safe' },
          { icon: '👚', text: 'Wardrobe or closet' },
          { icon: '⬆️', text: 'Upper floors accessible by elevator' },
          { icon: 'hangers', text: 'Clothes rack' },
          { icon: '🧻', text: 'Toilet paper' },
          { icon: '🧴', text: 'Hand sanitizer gel' },
        ],
        paymentCancellation: [
          { icon: '✔️', text: 'Free cancellation at any time' },
          { icon: '💳', text: 'No prepayment needed – pay at the accommodation' },
          { icon: '❌', text: 'No credit card required' },
        ],
      },
      {
        id: 'presidente-duplo-deluxe',
        name: 'Quarto Duplo Deluxe',
        guestCapacity: {
          maxPeople2: 2,
          price2_breakfast_only: 1760 * USD_TO_AOA_RATE,
          price2_breakfast_dinner: 2056 * USD_TO_AOA_RATE,
          maxPeople1: 1,
          price1_breakfast_only: 1650 * USD_TO_AOA_RATE,
          price1_breakfast_dinner: 1798 * USD_TO_AOA_RATE,
        },
        bedding: '1 cama de casal grande',
        area: '40 m²',
        images: [
          '/hotels/Presidente/Quarto Duplo Delux/1.jpg', // Placeholder
          '/hotels/Presidente/Quarto Duplo Delux/2.jpg', // Placeholder
        ],
        amenities: [
          { icon: '👶', text: 'Crib: Available upon request' },
          { icon: '🍳', text: 'Private Kitchenette' },
          { icon: '🌊', text: 'Sea view' },
          { icon: '🍽️', text: 'Dishwasher' },
          { icon: '🧺', text: 'Minibar' },
          { icon: '📶', text: 'Free Wi-Fi' },
          { icon: '🚿', text: 'Private bathroom' },
          { icon: '📺', text: 'Flat-screen TV' },
          { icon: '🔇', text: 'Soundproofing' },
          { icon: '🧴', text: 'Free toiletries' },
          { icon: '🚿', text: 'Shower' },
          { icon: '🔒', text: 'Safe' },
          { icon: '🚻', text: 'WC' },
          { icon: '🧼', text: 'Towels' },
          { icon: '🛏️', text: 'Bed linen' },
          { icon: '🔌', text: 'Socket near the bed' },
          { icon: '🖥️', text: 'Desk' },
          { icon: '🛋️', text: 'Seating area' },
          { icon: '🚪', text: 'Private entrance' },
          { icon: '📺', text: 'Television' },
          { icon: '🩴', text: 'Slippers' },
          { icon: '🧊', text: 'Fridge' },
          { icon: '📞', text: 'Telephone' },
          { icon: '👕', text: 'Ironing facilities' },
          { icon: '☕', text: 'Tea and coffee making facilities' },
          { icon: '🎞️', text: 'Pay-per-view channels' },
          { icon: 'hairdryer', text: 'Hair dryer' },
          { icon: '⏰', text: 'Wake-up service/alarm clock' },
          { icon: '🧶', text: 'Carpeted floor' },
          { icon: 'Kettle', text: 'Electric kettle' },
          { icon: '📺', text: 'Cable channels' },
          { icon: '⏰', text: 'Wake-up service' },
          { icon: '💻', text: 'Laptop safe' },
          { icon: '👚', text: 'Wardrobe or closet' },
          { icon: '⬆️', text: 'Upper floors accessible by elevator' },
          { icon: 'hangers', text: 'Clothes rack' },
          { icon: '🧻', text: 'Toilet paper' },
          { icon: '🧴', text: 'Hand sanitizer gel' },
        ],
        paymentCancellation: [
          { icon: '✔️', text: 'Free cancellation at any time' },
          { icon: '💳', text: 'No prepayment needed – pay at the accommodation' },
          { icon: '❌', text: 'No credit card required' },
        ],
      },
      {
        id: 'presidente-twin-deluxe',
        name: 'Quarto Twin Deluxe',
        guestCapacity: {
          maxPeople2: 2,
          price2_breakfast_only: 1760 * USD_TO_AOA_RATE,
          price2_breakfast_dinner: 2056 * USD_TO_AOA_RATE,
          maxPeople1: 1,
          price1_breakfast_only: 1650 * USD_TO_AOA_RATE,
          price1_breakfast_dinner: 1798 * USD_TO_AOA_RATE,
        },
        bedding: '2 camas de solteiro',
        area: '40 m²',
        images: [
          '/hotels/Presidente/Quarto Twin Delux/1.jpg', // Placeholder
          '/hotels/Presidente/Quarto Twin Delux/2.jpg', // Placeholder
        ],
        amenities: [
          { icon: '👶', text: 'Crib: Available upon request' },
          { icon: '🍳', text: 'Private Kitchenette' },
          { icon: '🍽️', text: 'Dishwasher' },
          { icon: '🧺', text: 'Minibar' },
          { icon: '📶', text: 'Free Wi-Fi' },
          { icon: '🚿', text: 'Private bathroom' },
          { icon: '📺', text: 'Flat-screen TV' },
          { icon: '🔇', text: 'Soundproofing' },
          { icon: '🧴', text: 'Free toiletries' },
          { icon: '🚿', text: 'Shower' },
          { icon: '🔒', text: 'Safe' },
          { icon: '🚻', text: 'WC' },
          { icon: '🧼', text: 'Towels' },
          { icon: '🛏️', text: 'Bed linen' },
          { icon: '🔌', text: 'Socket near the bed' },
          { icon: '🖥️', text: 'Desk' },
          { icon: '🛋️', text: 'Seating area' },
          { icon: '🚪', text: 'Private entrance' },
          { icon: '📺', text: 'Television' },
          { icon: '🩴', text: 'Slippers' },
          { icon: '🧊', text: 'Fridge' },
          { icon: '📞', text: 'Telephone' },
          { icon: '👕', text: 'Ironing facilities' },
          { icon: '☕', text: 'Tea and coffee making facilities' },
          { icon: '🎞️', text: 'Pay-per-view channels' },
          { icon: 'hairdryer', text: 'Hair dryer' },
          { icon: '⏰', text: 'Wake-up service/alarm clock' },
          { icon: '🧶', text: 'Carpeted floor' },
          { icon: 'Kettle', text: 'Electric kettle' },
          { icon: '📺', text: 'Cable channels' },
          { icon: '⏰', text: 'Wake-up service' },
          { icon: '💻', text: 'Laptop safe' },
          { icon: '👚', text: 'Wardrobe or closet' },
          { icon: '⬆️', text: 'Upper floors accessible by elevator' },
          { icon: 'hangers', text: 'Clothes rack' },
          { icon: '🧻', text: 'Toilet paper' },
          { icon: '🧴', text: 'Hand sanitizer gel' },
        ],
        paymentCancellation: [
          { icon: '✔️', text: 'Free cancellation at any time' },
          { icon: '💳', text: 'No prepayment needed – pay at the accommodation' },
          { icon: '❌', text: 'No credit card required' },
        ],
      },
    ],
  },
];

export default hotels;
